DECLARE

CURSOR c_plata_evento_l IS
    SELECT
    L_E.LOCALIDAD_EVENTO_ID,
    R_T.ESTADO,
    L_E.PRECIO
    FROM RESERVA_TEMPORAL R_T
    JOIN LOCALIDAD_EVENTO L_E ON L_E.LOCALIDAD_EVENTO_ID=R_T.LOCALIDAD_EVENTO_ID
    WHERE R_T.ESTADO = 'CONVERTIDA';
BEGIN
    null;
END;
/
SELECT * FROM RESERVA_TEMPORAL
SELECT * FROM LOCALIDAD_EVENTO


    